version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore NewsLetter/NewsLetter.sln
build:
  project: NewsLetter/NewsLetter.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal