version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore NewsLetter/NewsLetter.sln
build:
  project: NewsLetter/NewsLetter.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: liyYSnJ4SfUDl+GjvANnmqgCR2tPbPrno6U62LgXcLaFWhgA1fZJd1wNMo8FbEhW

after_test:
  - NewsLetter\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"NewsLetter\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single NewsLetter\Tests\NewsLetter.Services.Data.Tests\bin\Debug\NewsLetter.Services.Data.Tests.dll" -output:cover.xml

  - NewsLetter\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml